# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    # Fix swift-actions/setup-swift#798
    - name: Import GPG keys
      run: |
        curl -LO https://swift.org/keys/automatic-signing-key-4.asc
        if gunzip -t automatic-signing-key-4.asc 2>/dev/null; then
          gunzip -c automatic-signing-key-4.asc | gpg --import
        else
          cat automatic-signing-key-4.asc | gpg --import
        fi
        curl -LO https://swift.org/keys/release-key-swift-6.x.asc
        if gunzip -t release-key-swift-6.x.asc 2>/dev/null; then
          gunzip -c release-key-swift-6.x.asc | gpg --import
        else
          cat release-key-swift-6.x.asc | gpg --import
        fi
    - uses: swift-actions/setup-swift@v3

    - name: Build
      run: swift build ${{ runner.debug == '1' && '--verbose' || '' }}
    - name: Build test code
      run: swift build --build-tests --enable-code-coverage ${{ runner.debug == '1' && '--verbose' || '' }}
    - name: Run tests
      run: swift test --skip-build --disable-xctest --enable-code-coverage ${{ runner.debug == '1' && '--verbose' || '' }}

    - name: Generate lcov report
      run: |
        BINARY_PATH="$(swift build --show-bin-path)"
        CODECOV_PATH="$(swift test --show-codecov-path | xargs dirname)"
        llvm-cov report -ignore-filename-regex="/.build/|/Tests/" -instr-profile "${CODECOV_PATH}/default.profdata" "${BINARY_PATH}/JSONCodablePackageTests.xctest" | sed 's/  \+/|/g;s/--\+/||||||||||||/;2s/|/-|/g;s/-|$/-|-/' >> "$GITHUB_STEP_SUMMARY"
